/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB3M3
 */
public class Tela1_GUI extends javax.swing.JFrame {
    public static String total;

    /**
     * Creates new form Tela1_GUI
     */
    public Tela1_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        preferencial = new javax.swing.JTextField();
        normal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imprime = new javax.swing.JButton();
        senha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        normalButton = new javax.swing.JButton();
        preferencialButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        preferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencialActionPerformed(evt);
            }
        });
        jPanel1.add(preferencial);
        preferencial.setBounds(560, 130, 200, 430);

        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        jPanel1.add(normal);
        normal.setBounds(330, 130, 200, 430);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ATENDIMENTO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 20, 430, 50);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NORMAL");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 100, 200, 23);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PREFERENCIAL");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(560, 99, 200, 23);

        imprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Placa-Retire-Sua-Senha-Verde.png"))); // NOI18N
        imprime.setBorderPainted(false);
        imprime.setContentAreaFilled(false);
        imprime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimeActionPerformed(evt);
            }
        });
        jPanel1.add(imprime);
        imprime.setBounds(490, 570, 100, 60);

        senha.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        senha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        senha.setText("A 16");
        jPanel1.add(senha);
        senha.setBounds(80, 250, 150, 80);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SENHA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 130, 150, 60);

        normalButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        normalButton.setText("Senha normal");
        normalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalButtonActionPerformed(evt);
            }
        });
        jPanel1.add(normalButton);
        normalButton.setBounds(10, 460, 300, 70);

        preferencialButton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        preferencialButton.setText("Senha preferencial");
        preferencialButton.setMaximumSize(new java.awt.Dimension(117, 23));
        preferencialButton.setMinimumSize(new java.awt.Dimension(117, 23));
        jPanel1.add(preferencialButton);
        preferencialButton.setBounds(10, 550, 300, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 630);

        setSize(new java.awt.Dimension(789, 671));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void preferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preferencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preferencialActionPerformed

    private void imprimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imprimeActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalActionPerformed

    private void normalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalButtonActionPerformed
        Random random = new Random();
   
        for(int c = 0 ; c < 5 ; c++){
            int valor = random.nextInt(1000);
   
            total = total + "A" +valor +"\n";
            JOptionPane.showMessageDialog(null, total + "SENHAS GERADAS");
        }
    }//GEN-LAST:event_normalButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imprime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField normal;
    private javax.swing.JButton normalButton;
    private javax.swing.JTextField preferencial;
    private javax.swing.JButton preferencialButton;
    private javax.swing.JTextField senha;
    // End of variables declaration//GEN-END:variables
}
