/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author LAB3M3
 */
public class Tela1_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Tela1_GUI
     */
    public Tela1_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Senha = new javax.swing.JTextField();
        primeiro = new javax.swing.JButton();
        primeiro1 = new javax.swing.JButton();
        primeiro2 = new javax.swing.JButton();
        primeiro3 = new javax.swing.JButton();
        primeiro4 = new javax.swing.JButton();
        primeiro5 = new javax.swing.JButton();
        ir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Senha.setBackground(new java.awt.Color(51, 51, 255));
        Senha.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Senha.setForeground(new java.awt.Color(51, 51, 255));
        Senha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });
        jPanel1.add(Senha);
        Senha.setBounds(280, 180, 310, 70);

        primeiro.setText("Primeiro");
        primeiro.setBorderPainted(false);
        primeiro.setContentAreaFilled(false);
        jPanel1.add(primeiro);
        primeiro.setBounds(20, 310, 380, 80);

        primeiro1.setText("quinto");
        primeiro1.setBorderPainted(false);
        primeiro1.setContentAreaFilled(false);
        jPanel1.add(primeiro1);
        primeiro1.setBounds(470, 540, 380, 80);

        primeiro2.setText("Segundo");
        primeiro2.setBorderPainted(false);
        primeiro2.setContentAreaFilled(false);
        jPanel1.add(primeiro2);
        primeiro2.setBounds(20, 420, 380, 80);

        primeiro3.setText("Sair");
        primeiro3.setBorderPainted(false);
        primeiro3.setContentAreaFilled(false);
        jPanel1.add(primeiro3);
        primeiro3.setBounds(20, 540, 380, 80);

        primeiro4.setText("Terceiro");
        primeiro4.setBorderPainted(false);
        primeiro4.setContentAreaFilled(false);
        jPanel1.add(primeiro4);
        primeiro4.setBounds(470, 310, 380, 80);

        primeiro5.setText("Quarto");
        primeiro5.setBorderPainted(false);
        primeiro5.setContentAreaFilled(false);
        jPanel1.add(primeiro5);
        primeiro5.setBounds(470, 420, 380, 80);

        ir.setText("IR");
        ir.setBorderPainted(false);
        ir.setContentAreaFilled(false);
        ir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irActionPerformed(evt);
            }
        });
        jPanel1.add(ir);
        ir.setBounds(770, 190, 80, 80);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/tela_04.png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 870, 667);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(885, 706));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhaActionPerformed

    private void irActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irActionPerformed
        new Tela2_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_irActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Senha;
    private javax.swing.JButton ir;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton primeiro;
    private javax.swing.JButton primeiro1;
    private javax.swing.JButton primeiro2;
    private javax.swing.JButton primeiro3;
    private javax.swing.JButton primeiro4;
    private javax.swing.JButton primeiro5;
    // End of variables declaration//GEN-END:variables
}
